### PR TITLE
Android arrow fix

### PR DESCRIPTION
**Pull request by redwolf2**
https://github.com/NPBruce/valkyrie/issues/922

### CODE REVIEW

**Comment by BenRQ** [comment]
Did you get a chance to try the "Font.HasCharacter()" call ?
Would be better if there a way to avoid changing the character, for devices that have the proper character.

**Comment by redwolf2** [comment]
@BenRQ That is a good idea, but I got lost. I downloaded all fonts from my phone in order to figure out, which one has the symbols. It must be one font, because arrows are working fine in Chrome and Firefox, but couldn't find it, even using tools like [charident ](https://blog.keyman.com/2011/07/character-identifier-tool/). I also considered including a font only for the arrow, but failed to wrap my head around FontForge. I cut corners after finding out, which the normal arrow is supported. I also considered using the right function to find out if the glyph is supported, but at that time I had the fix and figured it took more time than it was worth the hassle. The best approach would still be to include a custom font and add it as a fallback to all other fonts. That way even platforms that don't have the symbol will show the arrow.

**Comment by BenRQ** [comment]
Using the Font.HasCharacter() is still a workaround.

The font is included in the import from MoM so it's very strange that it does not show up on your phone.
I guess the problem is because the app is using the system fonts rather than the one imported in the project in the project.

In this file, you may want to check if the case sensitivity of the path is important :
unity\Assets\Scripts\GameType.cs

For example : 
    public override Font GetFont()
    {
-        return (Font)Resources.Load("fonts/MADGaramondPro");
+        return (Font)Resources.Load("Fonts/MADGaramondPro");
    }

**Comment by redwolf2** [comment]
I also tried the case sensive suggestion. That's not the problem. Most fonts don't include that symbol. I also installed MADGaramondPro on my machine. The font does not contain the glyph ➤, it will come from a fallback font on the system. 

charident

I will try out Font.HasCharacter().

**Comment by BenRQ** [comment]
Yes, in that case our choice of character is problematic ....
We could add one of these fonts in the app if they are free of rights.
Or try to find one font free with this character.

**Comment by redwolf2** [comment]
Noto font from Google

**Comment by redwolf2** [comment]
Ok, I think it is ready now.

* Added Google Noto Symbols als a fallback to all fonts
* Fixed arrow centering on button on all platforms, because the same font is used for all platforms, instead of relying on the system for fonts, which might scale different
* Changed the paths to match the correct case (even though that didn't seem to cause a problem)

**Pull request merged**
