### PR TITLE
New component varibles to be used in texts. 

### PR DESCRIPTION
**Pull request by eorahil**
* Event: Replaced with the text of the event
* Tile: Replaced with the name of the Tile
* Token: Replaced with the text of the token
* CustomMonster: Replaced with the custom monster name
* Spawn: Replaced with the text shown in the spawn
* QItem: I want to show the QItem name but it has many i'm not sure. I will print a name of the first element in the list.

More types of components can be added if needed.

### CODE REVIEW

**Comment by eorahil** [comment]
Texts of events,tokens and spawns can be used to avoid the insertion of 2 localization strings that are the same.  a token can have a text and the event that shows the token can inherit his text by referencing it in the event text.

**Comment by NPBruce** [comment]
> Texts of events,tokens and spawns can be used to avoid the insertion of 2 localization strings that are the same. a token can have a text and the event that shows the token can inherit his text by referencing it in the event text.

We can do this already with {qst:.  The only difference is that {qst is resolved in the editor, but I want thinking that it would be better if it wasn't.  Thoughts?

**Comment by eorahil** [comment]
Manual insertion of qst should be made with external editors in order to optimize or reduce localization texts. In some cases we can use the new q variables. 
I think qst should still be replaced in editor. We should find other ways to reduce the localization files and duplicated texts. For example the Continue texts, in almost every event. should be a {qst:CONTINUE} by default. And if someone edits it, the new text will be used.

**Comment by NPBruce** [comment]
In either case this special version of qst: that isn't replaced should be a different tag to the c: that has very different functionality.  For 1.1 my preference is to drop this feature (the qst: text reference alternative) and sort in out in 1.2.

**Pull request merged**
