### PR TITLE
Added russian

### PR DESCRIPTION
**Pull request by redwolf2**
https://github.com/NPBruce/valkyrie/issues/999

"Japanese" is removed, because it isn't available yet and russian had to fit into the screen.

Translations where done by @Ssid113

### CODE REVIEW

**Comment by BenRQ** [comment]
Looks good to me :)
I will integrate it just after the new scenario explorer, and add the new texts along with it.

Memo: Also I need to support Russian there

**Comment by Dlaha** [comment]
Objection 😺  People from Czech community are currently working on Czech translation and would like to prepare a merge request soon. Is it possible not to remove Czech and make enought space for all languages?

**Comment by redwolf2** [comment]
Of course it is. Just send in the translated text as seen here: https://github.com/NPBruce/valkyrie/issues/999

**Comment by redwolf2** [comment]
@Dlaha Ok, I readded czech.

**Pull request merged**
