### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by LordPyrex**
New updates to scenario

### CODE REVIEW

**Comment by NPBruce** [comment]
Two things:

1: This package name has spaces which is broken.  Please rename the directory your quest is in before making the package.

2: No need for a pull request.  I can just change the list to point at https://github.com/LordPyrex/valkyrie-questdata/tree/master/source/MoM now, which is your repo and you can update whenever you like.

Let me know whent the spaces are fixed and I will update the reference.

**Comment by LordPyrex** [comment]
Just re-uploaded with no spaces.

**Comment by NPBruce** [comment]
Where?  Only one I see still has spaces.

**Comment by NPBruce** [comment]
Also the tile image has spaces.

**Comment by LordPyrex** [comment]
Oh, I understand what you mean, contents... does this hold for all the
files, all the way down to whats in the valkyrie file?

**Comment by NPBruce** [comment]
https://github.com/NPBruce/valkyrie/wiki/QuestPublish

Actually realised the image is also missing.

When you package you should get a directory with 2/3 files (2 if you don't use a thumbnail).

All three of these files, plus the directory itself should not have spaces.

Any files inside the package don't matter.

**Comment by LordPyrex** [comment]
Fully fixed.
https://github.com/LordPyrex/valkyrie/tree/master/InPlacesUnseen

**Comment by NPBruce** [comment]
Done!  Now you can update it any time.

**Comment by LordPyrex** [comment]
Thanks Bruce! Need help with anything that I can handle?

**Comment by NPBruce** [comment]
The big thing that I want to do is Android support, but I need to find a big block of time to learn more about how android works, which I can't do right now.  I think in general Valkyrie is in a pretty good state, should do most of what most people want.

**Comment by LordPyrex** [comment]
I agree. The project has definitely come very far! It does everything that
I think is needed to make shareable scenarios. I guess one thing that could
be figured out is the scenario feedback. We could look to opening a message
board with links back to GitHub.

**Pull request closed without merging**
