### PR TITLE
Polish Localization.

### PR DESCRIPTION
**Pull request by chmod555**
Hi.
I've created Polish translation for Localization.txt and Localization.Polish.txt files.
Hope that helps.
BR
Piotr 

_Sent from my Meizu m2 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

### CODE REVIEW

**Comment by NPBruce** [comment]
Great thanks!  Will be in the next build.

**Comment by chmod555** [comment]
Great. If You will get some negative feedback about this translation - just let me know. I'll try harder:)

**Comment by Venosthe** [comment]
Are there any more files, that have to be translated into polish? I'm working onto polish scenario and I would like to see polish buttons and mythos into Valkyrie. If help needed - let me know.

**Comment by NPBruce** [comment]
We already do that.  All the mythos and other game text is taken from MoM.  The translations are for Valkyrie specific interface text (mostly the editor) and scenarios.  For more see here:

https://github.com/NPBruce/valkyrie/wiki/Translations

There are a few items missing Polish translations, but nothing too important.  Some things don't fit in their text box and overlap.  You can edit the translations and fix things up a bit and provide the improved Localization.Polish.txt file and I will update it.

**Pull request merged**
