### PR TITLE
Localization fixes: Added keys for default texts, fixed mythos events import and mythos.ini file

### PR DESCRIPTION
**Pull request by eorahil**

### CODE REVIEW

**Comment by eorahil** [comment]
And atack types

**Comment by NPBruce** [comment]
Do you mind changing the target to development? Right now both code bases are the same, but I want to put only bug fixes into master to keep it stable. Development will merge to master for a 1.1 release.

**Comment by eorahil** [comment]
Sorry. My mistake

**Comment by NPBruce** [comment]
I will manually apply the things that affect translations on playing quests (mostly mythos.ini) to master for release in 1.0.

**Pull request merged**
