### PR TITLE
Update Localization.txt

### PR DESCRIPTION
**Pull request by Landar77**
Update 2.0 italian transale.

### CODE REVIEW

**Comment by redwolf2** [comment]
You forgot SELECT_TO_DELETE

**Comment by eorahil** [comment]
Sorry. I forgot EVENT_DOOR_DEFAULT_TEXT

but SELECT_TO_DELETE was in the first version

**Comment by redwolf2** [comment]
I merged it with this pull request https://github.com/NPBruce/valkyrie/pull/275

**Comment by NPBruce** [comment]
Merged in #275

**Pull request closed without merging**
