### PR TITLE
Changed all multiline editable boxes with the buttons version

### PR DESCRIPTION
**Pull request by eorahil**
Changed all multiline editable boxes with the buttons version
Translated some new texts
added the {rnd:hero} button

I try to reproduce #374  but I cant.

### CODE REVIEW

**Comment by eorahil** [comment]
Also created string constants for tags and a new menu option (disabled for now) with tools to:
- optimize a localization file: find dupes and create new keys for these
- export localization file: create a single language localization to translate easier.
- import localization file: imports the single language localization files to the main one
- scenario validator: all possible checks could be inside.

**Comment by redwolf2** [comment]
Added german translation https://github.com/eorahil/valkyrie/pull/2

**Comment by NPBruce** [comment]
From #389:

unity/Assets/Plugins/UnityEngine.xml has mistakenly replaced text

"activation" as a tag has been missed.

I think changing the format on disk makes more sense than creating a new import/export format, and will make version control much better.

**Comment by eorahil** [comment]
The problem with various localization files are that you lose control of all the translation. If you want to refactor some text because you know it's repeated or you want to combine texts with the {qst:key:{0}:{qst:otherkey}} you must be aware of all the translation files. changing references in all files removing or adding keys. 
I think the one file format is better for global scenario manipulations. BUT I still know that merging a new language is a non automatic job (the merge is not automated) so there is an additional work to do and people can make mistakes while merging and break the file structure.
That's why I decided to introduce the import/export tools. Someone can send his translations to the scenario creator and the creator can import the localization file into his scenario. but creator can reorder, refector some entryes with total control of all texts.

**Comment by NPBruce** [comment]
If you are using the editor it makes no difference how many files it is.  If you are editing manually and changing element names you probably need to redo all of the translations anyway, so I honestly don't see an issue.

On the other hand adding another interface and tool for people to use WILL complicate the work flow.  Translations need to be as simple as possible for people who are not developers, and ideally don't even need to run Valkyrie.

**Comment by NPBruce** [comment]
I will approve this change, but do not want the import/export feature.  I am happy to do the localization file split myself.

**Comment by eorahil** [comment]
Ok, no problem I only wanted other oppinions. I can split the localization file.
should I keep the tools submenu for validating and optimizing localization? or these thinks should be automated when saving?

**Comment by NPBruce** [comment]
I am planning to redo that part of the UI at some point so it doesn't really matter much.  You can leave them there or move them to the menu.

**Pull request merged**
