### PR TITLE
Mad28: Path Of The Serpent

### PR DESCRIPTION
**Pull request by redwolf2**
https://github.com/NPBruce/valkyrie/issues/1204

### CODE REVIEW

**Comment by NPBruce** [comment]
Thanks for doing this work. A few things:

1: Items and tokens ini files are referenced but not included.

2: When adding support for new content the format should be incremented, so that new work targetting this content won't break existing builds.

3: Adding the monsters also requires adding evades, attacks (if not existing), activations and horror checks.

4: Symbol should be added in Valkyrie.

Additional Mythos is nice, but can be added later without issue.

**Comment by redwolf2** [comment]
@NPBruce Thx, I am not done, all WIP, but I will add all your suggestions in ;)

**Comment by redwolf2** [comment]
OK, all done. There were no special evade, attack or horror checks for the new monsters though.

**Comment by scrubbless** [comment]
@npbruce I assume this needs checking before commit?

**Comment by BenRQ** [comment]
Merging for clarification, it has already been merged with #1272

**Pull request merged**
