### PR TITLE
Reverse tiles and traits info

### PR DESCRIPTION
**Pull request by eorahil**
reverse tiles and traits info.

### CODE REVIEW

**Comment by eorahil** [comment]
modified branch to include D2E reverses

**Comment by NPBruce** [comment]
Please merge from my development branch into this.  Then your branch will support this feature for testing.

**Comment by NPBruce** [comment]
You don't have to close a pull request to make changes, you can just commit/merge to your branch and this will update.

It might be easier though to name your branch something other than 'development' to use NPBruce.development and eorahil.current_task - you can create a new branch for each task and sourcetree is slightly less confusing if the branch names are different.

**Comment by eorahil** [comment]
Sorry. I messed all and deleted job done. Last night work to the trash.. T_T.
I didn't backup and lost everything trying to merge

**Comment by eorahil** [comment]
could you casually have a local version of the changes made by me last night?

**Comment by NPBruce** [comment]
I have added your commits to a new branch in my repository and created a new pull request here:

https://github.com/NPBruce/valkyrie/pull/59

Please have a look and check that it is correct.

I have not lost anything.

**Comment by eorahil** [comment]
Thanks for recovering, I made a reset from my branch to rebase yours and I lost all history. But you could get it, thanks.

**Pull request closed without merging**
