### PR TITLE
Fixed already localized scenarios import. Translated some select items lists.

### PR DESCRIPTION
**Pull request by eorahil**
The fix is to not include in dictionary the key itself if it was still in the saved file. This resulted in saving {qst:quest.name} as the translated text of this key. so Translate came into infinite look because when the translator, after translating sees another key it tries to translate it again, and again ,and again, ...

I translated some lists. The TileSides and the monster names. Updated tileSides ini files to include the ffg names.

I alread changed your getQuery method to return directly the StringKey item. I did it because a 
new StringKey(string param1) is the slowest constructor for a known key. This constructor must analyze the string param1 and divide the dictionary from the key and from the params.
The correct in this case should be new StringKey("qst",string onlykey)
so 
new StringKey("qst","quest.name") 
is faster than
new StringKey("{qst:quest.name}")

### CODE REVIEW

**Comment by NPBruce** [comment]
> The fix is to not include in dictionary the key itself if it was still in the saved file. This resulted in saving {qst:quest.name} as the translated text of this key. so Translate came into infinite look because when the translator, after translating sees another key it tries to translate it again, and again ,and again, ...

This specific problem only exists in a hybrid 2/3 format which only you will have.  Using name= is now obsolete.  Fixing the problem is nice, however it still exists if you have:

> name,"{qst:name}",""

Or more complicated examples with loops of queries.  So the better fix would be to limit the recursion depth on the lookup itself.

As a side note if these three issues could be separate pull requests it is easier to approve the other two.

**Comment by eorahil** [comment]
Ok. no problem It takes me more time to split the files so I will implement the loop detector

**Comment by eorahil** [comment]
Fixed. Added a counter of recursive calls. I put the limit to 10. If you think itsn't enought we can increase but I considered 10 stringkeys references inside a text are enought.
If the limit is reached it stops resolving translations and returns the current translation.
I tested a self-referenced key and 3 cycle-referenced keys.

**Comment by NPBruce** [comment]
Great, 10 sounds good.

**Pull request merged**
