### PR TITLE
Feature/find macos resources

### PR DESCRIPTION
**Pull request by foskon**
- Extraction of platform code to a new class. I have also add "RuntimePlatform.OSXEditor" to the check for debugging on Unity without building.
- I have used System.Xml and the build was crashing because the Api Compatibility Level was .NET 2.0 subset, so i changed it to .NET 2.0. Don't know if this is a problem or if there is another library I can use instead of System.Xml. (https://forum.unity3d.com/threads/problem-when-loading-xml-at-runtime.141705/)
- Resources of MoM are imported correctly.

Please, review my code because I am not c# developer.

### CODE REVIEW

**Comment by NPBruce** [comment]
Can you please change your editor settings to preserve spaces (and/or only use space indents)?  I am using VS (it is good for debugging) and that uses spaces for everything, so the white space changes makes it hard to see your actual code changes.

**Comment by foskon** [comment]
Yeah, no problem. I will update the pr without white spaces.

**Comment by NPBruce** [comment]
Only downside on moving away from subset is build size.  How big does your build end up?

**Comment by foskon** [comment]
310,5 MB

**Comment by NPBruce** [comment]
Mine is at 53 uncompressed for macos (19 compressed).  Sounds OK.

**Comment by NPBruce** [comment]
Closing this as dev branch has departed significantly and white space issue unresolved.

Current solution doesn't read XML properly, but seems to work.

**Pull request closed without merging**
